---
title: "World Bank Data Analysis"
author: "Adrian Glapiński"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
  html_document: 
    keep_md: false
    df_print: kable
    code_folding: "hide"
    toc: true
    toc_float: true
    #number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Executive summary
TODO

## Used libraries

```{r load-libraries, message=FALSE, collapse=FALSE}
library(knitr)
library(kableExtra)
library(DT)

library(tidyverse)
library(readxl)
library(lubridate)
library(janitor)

library(skimr)
library(gtsummary)
#library(summarytools)
#library(desctable)

library(corrr)
#library(corrplot)

library(ggplot2)
library(ggthemes)
library(gganimate)
library(plotly)

library(caret)
library(missForest)

library(countrycode)
```

## Load data
```{r load-data, message=FALSE}
wdi_df <- read_excel('./data/World_Development_Indicators.xlsx', 
                 na = c('', '..')) %>% head(-5)

currency_df <- read_csv('./data/CurrencyExchangeRates.csv', 
                        col_types = cols(Date = col_date("%Y-%m-%d")))

# https://data.nasdaq.com/data/LBMA/GOLD-gold-price-london-fixing
gold_prices_df <- read_csv('./data/Gold prices.csv')

# https://data.nasdaq.com/data/YALE/SPCOMP-sp-composite
sp_df <- read_csv('./data/S&P Composite.csv')

# https://data.nasdaq.com/data/BCHAIN-blockchain
btc_diff_df <- read_csv('./data/bitcoin/BCHAIN-DIFF.csv')
btc_hrate_df <- read_csv('./data/bitcoin/BCHAIN-HRATE.csv')
btc_mkpru_df <- read_csv('./data/bitcoin/BCHAIN-MKPRU.csv')
btc_trvou_df <- read_csv('./data/bitcoin/BCHAIN-TRVOU.csv')
```

## Clean data sets

```{r clean-data-sets}
wdi_cleaned_df <- wdi_df %>%
  select(-c(`Country Code`, `Series Code`)) %>%
  pivot_longer(-c(`Country Name`, `Series Name`), names_to = 'Year') %>%
  pivot_wider(names_from = `Series Name`) %>%
  mutate(`Country Name` = as_factor(`Country Name`),
         Year = as.numeric(word(Year))) 

wdi_names <- names(wdi_cleaned_df) %>% 
  set_names(make_clean_names(.)) %>%
  as.list
wdi_cleaned_df <- set_names(wdi_cleaned_df, names(wdi_names))

#currency_df <- clean_names(currency_df)
currency_df <- currency_df %>%
  pivot_longer(cols = -Date, names_to = 'currency',
               values_to = 'exchange_rate') %>%
  clean_names() %>%
  mutate(currency = as_factor(currency))

gold_prices_df <- clean_names(gold_prices_df)

sp_df <- clean_names(sp_df) %>% rename(date = year)

btc_diff_df <- clean_names(btc_diff_df)
btc_hrate_df <- clean_names(btc_hrate_df)
btc_mkpru_df <- clean_names(btc_mkpru_df)
btc_trvou_df <- clean_names(btc_trvou_df)

btc_df <- btc_diff_df %>%
  full_join(btc_hrate_df, by = 'date', suffix = c('_diff', '_hrate')) %>%
  full_join(btc_mkpru_df, by = 'date') %>% 
  full_join(btc_trvou_df, by = 'date', suffix = c('_mkpru', '_trvou')) %>%
  rename(difficulty = value_diff,
         hash_rate = value_hrate,
         market_price_usd = value_mkpru,
         exchange_trade_volume_usd = value_trvou)
```

## Data set summary

```{r}
tribble(
  ~Table, ~`No. of columns (attributes)`, ~`No. of rows (observations)`,
  'World Development Indicators', ncol(wdi_cleaned_df), nrow(wdi_cleaned_df),
  'Currency Exchange Rates', ncol(currency_df), nrow(currency_df),
  'Gold prices', ncol(gold_prices_df), nrow(gold_prices_df),
  'S&P Composite', ncol(sp_df), nrow(sp_df),
  'Bitcoin', ncol(btc_df), nrow(btc_df)
) %>% kbl() %>% kable_styling()
```
### World Development Indicators
```{r}
wdi_skim_df <- wdi_cleaned_df %>% 
  set_names(wdi_names) %>%
  skim() 
wdi_skim_df %>%
  yank('factor') %>% 
  clean_names(case = 'title') %>%
  datatable(options = list(scrollX = TRUE))
wdi_skim_df %>%
  yank('numeric') %>% 
  clean_names(case = 'title') %>%
  datatable(options = list(scrollX = TRUE)) %>% 
  formatRound(3:10)
```
### Currency Exchange Rates
```{r}
currency_df %>% 
  clean_names(case = 'title') %>%
  skim() %>% 
  clean_names(case = 'title') %>%
  datatable(options = list(scrollX = TRUE)) %>% 
  formatRound(c(3:6, 8, 10:15))
```
### Gold prices
```{r}
gold_prices_df %>% 
  clean_names(case = 'title', abbreviations = c('USD', 'GBP', 'AM', 'PM')) %>%
  skim() %>%
  clean_names(case = 'title') %>%
  datatable(options = list(scrollX = TRUE)) %>% 
  formatRound(3:14)
```
### S&P Composite
```{r}
sp_df %>% 
  clean_names(case = 'title', abbreviations = c('CPI')) %>% 
  rename(`S&P Composite` = `S p Composite`) %>%
  skim() %>% 
  clean_names(case = 'title') %>%
  datatable(options = list(scrollX = TRUE)) %>% 
  formatRound(3:15)
```
### Bitcoin
```{r}
btc_df %>% 
  clean_names(case = 'title', abbreviations = c('USD')) %>%
  skim() %>%
  clean_names(case = 'title') %>%
  datatable(options = list(scrollX = TRUE)) %>% 
  formatRound(3:13)
```
```{r}
#wdi_cor_df <- wdi_cleaned_df %>%
#  set_names(wdi_names) %>%
#  select(where(~mean(is.na(.)) < 0.25)) %>%
#  select(3:last_col()) %>%
#  correlate() %>%
#  shave() %>%
#  stretch() %>%
#  filter(abs(r) > 0.6, abs(r) < 0.99) %>%
#  arrange(desc(abs(r)))
#datatable(wdi_cor_df) %>% formatRound(3, digits = 5)
```

```{r map-plot}
# TODO Logarithmic scale for colorbar
wdi_continents_df <- wdi_cleaned_df %>% 
  filter(!country_name %in% c('Channel Islands', 'Kosovo', 
                              'Low & middle income', 'Low income', 
                              'Lower middle income', 'Middle income', 'World',
                              'Upper middle income', 'High income')) %>%
  add_column(continent = countrycode(sourcevar = .$country_name,
                                     origin = "country.name",
                                     destination = "continent")) %>%
  relocate(continent)

wdi_continents_df %>%
  plot_geo(locationmode = 'country names') %>%
  add_trace(z = ~gdp_per_capita_current_us, #zmin = 20, zmax = 150000, 
            color = ~gdp_per_capita_current_us,
            frame = ~year, 
            colors = 'Blues',
            text = ~country_name,
            locations = ~country_name,
            marker = list(line = list(color = toRGB("grey"), width = 0.5))) %>%
  colorbar(title = 'GDP per capita (USD)') %>% 
  layout(title = 'GDP per capita over years', 
         geo = list(scope = 'world',
                    countrycolor = toRGB('grey'),
                    showcoastlines = TRUE)) %>%  
  animation_opts(redraw = F) %>%  
  plotly_build()
```

```{r animated-plot, message = FALSE, eval=FALSE}
wdi_continents_df %>%
  ggplot(aes(gdp_per_capita_current_us, 
             life_expectancy_at_birth_total_years, 
             size = population_total, 
             color = continent)) +
  geom_point(alpha = 0.7) +
  scale_size_continuous(name = "Population",
                        breaks = c(1e9, 1e8, 1e7, 1e6),
                        limits = c(1e6, 1e9),
                        range = c(1, 8)) +
  scale_x_log10(labels = scales::comma) +
  theme_bw(base_size = 8) +
  labs(title = "{round(frame_time)}", 
       x = 'GDP per capita (USD)',
       y = 'Life expectancy (years)', 
       color = "Continent",
       caption = "") +
  transition_time(year) +
  ease_aes('linear') 
```

```{r}
yearly_gold_prices_df <- gold_prices_df %>% 
  mutate(date, gold_price_usd = ifelse(is.na(usd_pm), usd_am, usd_pm)) %>%
  group_by(year = year(date)) %>% 
  summarize(gold_price_usd = mean(gold_price_usd))

#yearly_sp_df <- sp_df %>% 
#  group_by(year = year(date)) %>%
#  summarize(sp_composite = mean(s_p_composite), 
#            sp_real_price = mean(real_price))

#yearly_btc_prices_df <- btc_df %>%
#  group_by(year = year(date)) %>%
#  summarize(btc_price = mean(market_price_usd))

world_wdi_gold_df <- wdi_cleaned_df %>%
  filter(country_name == 'World') %>% 
  inner_join(yearly_gold_prices_df, by = 'year') %>%
  remove_empty() 

#world_gold_cor <- world_wdi_gold_df %>%
#  select(3:last_col(offset = 1)) %>%
#  select(where(~mean(is.na(.)) < 0.25)) %>%
#  cor(., world_wdi_gold_df$gold_price_usd) %>% 
#  as_tibble(rownames = "variable") %>%
#  rename(r = V1) %>% 
#  drop_na() %>% 
#  filter(abs(r) > 0.6) %>% 
#  arrange(desc(abs(r)))

world_gold_cor <- world_wdi_gold_df %>% 
  select(3:last_col()) %>%
  select(where(~mean(is.na(.)) < 0.25)) %>%
  correlate() %>% 
  focus(gold_price_usd) %>% 
  arrange(desc(abs(gold_price_usd))) %>% 
  filter(abs(gold_price_usd) > 0.6, abs(gold_price_usd) < 0.99)
```

```{r regressor, eval=FALSE} 
set.seed(23)

miss_forest <- world_wdi_gold_df %>%
  select(where(~mean(is.na(.)) < 0.25)) %>%
  select_if(is.numeric) %>%
  as.data.frame() %>%
  missForest() 

print(miss_forest$OOBerror)

imputed_df <- miss_forest$ximp

train_index <- createDataPartition(imputed_df$gold_price_usd, 
                                   p = .70, 
                                   list = FALSE)
train_data <- imputed_df[train_index,]
test_data <- imputed_df[-train_index,]

ctrl <- trainControl(method = "repeatedcv",
                     number = 5,
                     repeats = 5)

fit <- train(gold_price_usd ~ .,
             data = train_data,
             method = "glmnet",
             trControl = ctrl)

#varImp(fit)
```